import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

import sun.misc.BASE64Encoder;

import java.io.*;
  
public class ChecksumFile { 
    public static String getMd5(String fileName) throws NoSuchAlgorithmException, IOException
    { 
        byte[] buffer= new byte[8192];
        int count;
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        BufferedInputStream bis = new BufferedInputStream(new FileInputStream(fileName));
        while ((count = bis.read(buffer)) > 0) {
            digest.update(buffer, 0, count);
        }
        bis.close();
    
        byte[] hash = digest.digest();
        return new BASE64Encoder().encode(hash);
    } 
    // Driver code 
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        Scanner scn = new Scanner(System.in);
        String file = scn.nextLine();
        try{
            System.out.println("Your HashCode Generated by SHA-256 is: " + getMd5(file)); 
            scn.close();
        }catch(Exception e){
            throw new RuntimeException(e);
        }
        
    } 
} 